// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Nebula.Spacetime.Persistence
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ClearPersistenceHandler(ReducerEventContext ctx);
        public event ClearPersistenceHandler? OnClearPersistence;

        public void ClearPersistence()
        {
            conn.InternalCallReducer(new Reducer.ClearPersistence());
        }

        public bool InvokeClearPersistence(ReducerEventContext ctx, Reducer.ClearPersistence args)
        {
            if (OnClearPersistence == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnClearPersistence(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ClearPersistence : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "clear_persistence";
        }
    }
}
