// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Nebula.Spacetime.Persistence
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeleteEntityHandler(ReducerEventContext ctx, string key);
        public event DeleteEntityHandler? OnDeleteEntity;

        public void DeleteEntity(string key)
        {
            conn.InternalCallReducer(new Reducer.DeleteEntity(key));
        }

        public bool InvokeDeleteEntity(ReducerEventContext ctx, Reducer.DeleteEntity args)
        {
            if (OnDeleteEntity == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDeleteEntity(
                ctx,
                args.Key
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeleteEntity : Reducer, IReducerArgs
        {
            [DataMember(Name = "key")]
            public string Key;

            public DeleteEntity(string Key)
            {
                this.Key = Key;
            }

            public DeleteEntity()
            {
                this.Key = "";
            }

            string IReducerArgs.ReducerName => "delete_entity";
        }
    }
}
