// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Nebula.Spacetime.Persistence
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SaveEntityHandler(ReducerEventContext ctx, string key, ushort prefabId, string prefabName, uint sceneId, string containerId, string carrierKey, float posX, float posY, float posZ, float rotX, float rotY, float rotZ, float rotW, float velX, float velY, float velZ, uint epoch, bool serverDriven, bool owned, string name, System.Collections.Generic.List<byte> state, string savedBy);
        public event SaveEntityHandler? OnSaveEntity;

        public void SaveEntity(string key, ushort prefabId, string prefabName, uint sceneId, string containerId, string carrierKey, float posX, float posY, float posZ, float rotX, float rotY, float rotZ, float rotW, float velX, float velY, float velZ, uint epoch, bool serverDriven, bool owned, string name, System.Collections.Generic.List<byte> state, string savedBy)
        {
            conn.InternalCallReducer(new Reducer.SaveEntity(key, prefabId, prefabName, sceneId, containerId, carrierKey, posX, posY, posZ, rotX, rotY, rotZ, rotW, velX, velY, velZ, epoch, serverDriven, owned, name, state, savedBy));
        }

        public bool InvokeSaveEntity(ReducerEventContext ctx, Reducer.SaveEntity args)
        {
            if (OnSaveEntity == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSaveEntity(
                ctx,
                args.Key,
                args.PrefabId,
                args.PrefabName,
                args.SceneId,
                args.ContainerId,
                args.CarrierKey,
                args.PosX,
                args.PosY,
                args.PosZ,
                args.RotX,
                args.RotY,
                args.RotZ,
                args.RotW,
                args.VelX,
                args.VelY,
                args.VelZ,
                args.Epoch,
                args.ServerDriven,
                args.Owned,
                args.Name,
                args.State,
                args.SavedBy
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SaveEntity : Reducer, IReducerArgs
        {
            [DataMember(Name = "key")]
            public string Key;
            [DataMember(Name = "prefab_id")]
            public ushort PrefabId;
            [DataMember(Name = "prefab_name")]
            public string PrefabName;
            [DataMember(Name = "scene_id")]
            public uint SceneId;
            [DataMember(Name = "container_id")]
            public string ContainerId;
            [DataMember(Name = "carrier_key")]
            public string CarrierKey;
            [DataMember(Name = "pos_x")]
            public float PosX;
            [DataMember(Name = "pos_y")]
            public float PosY;
            [DataMember(Name = "pos_z")]
            public float PosZ;
            [DataMember(Name = "rot_x")]
            public float RotX;
            [DataMember(Name = "rot_y")]
            public float RotY;
            [DataMember(Name = "rot_z")]
            public float RotZ;
            [DataMember(Name = "rot_w")]
            public float RotW;
            [DataMember(Name = "vel_x")]
            public float VelX;
            [DataMember(Name = "vel_y")]
            public float VelY;
            [DataMember(Name = "vel_z")]
            public float VelZ;
            [DataMember(Name = "epoch")]
            public uint Epoch;
            [DataMember(Name = "server_driven")]
            public bool ServerDriven;
            [DataMember(Name = "owned")]
            public bool Owned;
            [DataMember(Name = "name")]
            public string Name;
            [DataMember(Name = "state")]
            public System.Collections.Generic.List<byte> State;
            [DataMember(Name = "saved_by")]
            public string SavedBy;

            public SaveEntity(
                string Key,
                ushort PrefabId,
                string PrefabName,
                uint SceneId,
                string ContainerId,
                string CarrierKey,
                float PosX,
                float PosY,
                float PosZ,
                float RotX,
                float RotY,
                float RotZ,
                float RotW,
                float VelX,
                float VelY,
                float VelZ,
                uint Epoch,
                bool ServerDriven,
                bool Owned,
                string Name,
                System.Collections.Generic.List<byte> State,
                string SavedBy
            )
            {
                this.Key = Key;
                this.PrefabId = PrefabId;
                this.PrefabName = PrefabName;
                this.SceneId = SceneId;
                this.ContainerId = ContainerId;
                this.CarrierKey = CarrierKey;
                this.PosX = PosX;
                this.PosY = PosY;
                this.PosZ = PosZ;
                this.RotX = RotX;
                this.RotY = RotY;
                this.RotZ = RotZ;
                this.RotW = RotW;
                this.VelX = VelX;
                this.VelY = VelY;
                this.VelZ = VelZ;
                this.Epoch = Epoch;
                this.ServerDriven = ServerDriven;
                this.Owned = Owned;
                this.Name = Name;
                this.State = State;
                this.SavedBy = SavedBy;
            }

            public SaveEntity()
            {
                this.Key = "";
                this.PrefabName = "";
                this.ContainerId = "";
                this.CarrierKey = "";
                this.Name = "";
                this.State = new();
                this.SavedBy = "";
            }

            string IReducerArgs.ReducerName => "save_entity";
        }
    }
}
