// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Nebula.Spacetime.Persistence
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PersistedEntity
    {
        [DataMember(Name = "key")]
        public string Key;
        [DataMember(Name = "prefab_id")]
        public ushort PrefabId;
        [DataMember(Name = "prefab_name")]
        public string PrefabName;
        [DataMember(Name = "scene_id")]
        public uint SceneId;
        [DataMember(Name = "container_id")]
        public string ContainerId;
        [DataMember(Name = "carrier_key")]
        public string CarrierKey;
        [DataMember(Name = "pos_x")]
        public float PosX;
        [DataMember(Name = "pos_y")]
        public float PosY;
        [DataMember(Name = "pos_z")]
        public float PosZ;
        [DataMember(Name = "rot_x")]
        public float RotX;
        [DataMember(Name = "rot_y")]
        public float RotY;
        [DataMember(Name = "rot_z")]
        public float RotZ;
        [DataMember(Name = "rot_w")]
        public float RotW;
        [DataMember(Name = "vel_x")]
        public float VelX;
        [DataMember(Name = "vel_y")]
        public float VelY;
        [DataMember(Name = "vel_z")]
        public float VelZ;
        [DataMember(Name = "epoch")]
        public uint Epoch;
        [DataMember(Name = "server_driven")]
        public bool ServerDriven;
        [DataMember(Name = "owned")]
        public bool Owned;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "state")]
        public System.Collections.Generic.List<byte> State;
        [DataMember(Name = "version")]
        public ulong Version;
        [DataMember(Name = "saved_at")]
        public SpacetimeDB.Timestamp SavedAt;
        [DataMember(Name = "saved_by")]
        public string SavedBy;

        public PersistedEntity(
            string Key,
            ushort PrefabId,
            string PrefabName,
            uint SceneId,
            string ContainerId,
            string CarrierKey,
            float PosX,
            float PosY,
            float PosZ,
            float RotX,
            float RotY,
            float RotZ,
            float RotW,
            float VelX,
            float VelY,
            float VelZ,
            uint Epoch,
            bool ServerDriven,
            bool Owned,
            string Name,
            System.Collections.Generic.List<byte> State,
            ulong Version,
            SpacetimeDB.Timestamp SavedAt,
            string SavedBy
        )
        {
            this.Key = Key;
            this.PrefabId = PrefabId;
            this.PrefabName = PrefabName;
            this.SceneId = SceneId;
            this.ContainerId = ContainerId;
            this.CarrierKey = CarrierKey;
            this.PosX = PosX;
            this.PosY = PosY;
            this.PosZ = PosZ;
            this.RotX = RotX;
            this.RotY = RotY;
            this.RotZ = RotZ;
            this.RotW = RotW;
            this.VelX = VelX;
            this.VelY = VelY;
            this.VelZ = VelZ;
            this.Epoch = Epoch;
            this.ServerDriven = ServerDriven;
            this.Owned = Owned;
            this.Name = Name;
            this.State = State;
            this.Version = Version;
            this.SavedAt = SavedAt;
            this.SavedBy = SavedBy;
        }

        public PersistedEntity()
        {
            this.Key = "";
            this.PrefabName = "";
            this.ContainerId = "";
            this.CarrierKey = "";
            this.Name = "";
            this.State = new();
            this.SavedBy = "";
        }
    }
}
