// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Nebula.Spacetime.Persistence
{
    public sealed partial class RemoteTables
    {
        public sealed class PersistedEntityHandle : RemoteTableHandle<EventContext, PersistedEntity>
        {
            public override string RemoteTableName => "persisted_entity";

            public sealed class CarrierKeyIndex : BTreeIndexBase<string>
            {
                protected override string GetKey(PersistedEntity row) => row.CarrierKey;

                public CarrierKeyIndex(PersistedEntityHandle table) : base(table) { }
            }

            public readonly CarrierKeyIndex CarrierKey;

            public sealed class ContainerIdIndex : BTreeIndexBase<string>
            {
                protected override string GetKey(PersistedEntity row) => row.ContainerId;

                public ContainerIdIndex(PersistedEntityHandle table) : base(table) { }
            }

            public readonly ContainerIdIndex ContainerId;

            public sealed class KeyUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(PersistedEntity row) => row.Key;

                public KeyUniqueIndex(PersistedEntityHandle table) : base(table) { }
            }

            public readonly KeyUniqueIndex Key;

            internal PersistedEntityHandle(DbConnection conn) : base(conn)
            {
                CarrierKey = new(this);
                ContainerId = new(this);
                Key = new(this);
            }

            protected override object GetPrimaryKey(PersistedEntity row) => row.Key;
        }

        public readonly PersistedEntityHandle PersistedEntity;
    }

    public sealed class PersistedEntityCols
    {
        public global::SpacetimeDB.Col<PersistedEntity, string> Key { get; }
        public global::SpacetimeDB.Col<PersistedEntity, ushort> PrefabId { get; }
        public global::SpacetimeDB.Col<PersistedEntity, string> PrefabName { get; }
        public global::SpacetimeDB.Col<PersistedEntity, uint> SceneId { get; }
        public global::SpacetimeDB.Col<PersistedEntity, string> ContainerId { get; }
        public global::SpacetimeDB.Col<PersistedEntity, string> CarrierKey { get; }
        public global::SpacetimeDB.Col<PersistedEntity, float> PosX { get; }
        public global::SpacetimeDB.Col<PersistedEntity, float> PosY { get; }
        public global::SpacetimeDB.Col<PersistedEntity, float> PosZ { get; }
        public global::SpacetimeDB.Col<PersistedEntity, float> RotX { get; }
        public global::SpacetimeDB.Col<PersistedEntity, float> RotY { get; }
        public global::SpacetimeDB.Col<PersistedEntity, float> RotZ { get; }
        public global::SpacetimeDB.Col<PersistedEntity, float> RotW { get; }
        public global::SpacetimeDB.Col<PersistedEntity, float> VelX { get; }
        public global::SpacetimeDB.Col<PersistedEntity, float> VelY { get; }
        public global::SpacetimeDB.Col<PersistedEntity, float> VelZ { get; }
        public global::SpacetimeDB.Col<PersistedEntity, uint> Epoch { get; }
        public global::SpacetimeDB.Col<PersistedEntity, bool> ServerDriven { get; }
        public global::SpacetimeDB.Col<PersistedEntity, bool> Owned { get; }
        public global::SpacetimeDB.Col<PersistedEntity, string> Name { get; }
        public global::SpacetimeDB.Col<PersistedEntity, System.Collections.Generic.List<byte>> State { get; }
        public global::SpacetimeDB.Col<PersistedEntity, ulong> Version { get; }
        public global::SpacetimeDB.Col<PersistedEntity, SpacetimeDB.Timestamp> SavedAt { get; }
        public global::SpacetimeDB.Col<PersistedEntity, string> SavedBy { get; }

        public PersistedEntityCols(string tableName)
        {
            Key = new global::SpacetimeDB.Col<PersistedEntity, string>(tableName, "key");
            PrefabId = new global::SpacetimeDB.Col<PersistedEntity, ushort>(tableName, "prefab_id");
            PrefabName = new global::SpacetimeDB.Col<PersistedEntity, string>(tableName, "prefab_name");
            SceneId = new global::SpacetimeDB.Col<PersistedEntity, uint>(tableName, "scene_id");
            ContainerId = new global::SpacetimeDB.Col<PersistedEntity, string>(tableName, "container_id");
            CarrierKey = new global::SpacetimeDB.Col<PersistedEntity, string>(tableName, "carrier_key");
            PosX = new global::SpacetimeDB.Col<PersistedEntity, float>(tableName, "pos_x");
            PosY = new global::SpacetimeDB.Col<PersistedEntity, float>(tableName, "pos_y");
            PosZ = new global::SpacetimeDB.Col<PersistedEntity, float>(tableName, "pos_z");
            RotX = new global::SpacetimeDB.Col<PersistedEntity, float>(tableName, "rot_x");
            RotY = new global::SpacetimeDB.Col<PersistedEntity, float>(tableName, "rot_y");
            RotZ = new global::SpacetimeDB.Col<PersistedEntity, float>(tableName, "rot_z");
            RotW = new global::SpacetimeDB.Col<PersistedEntity, float>(tableName, "rot_w");
            VelX = new global::SpacetimeDB.Col<PersistedEntity, float>(tableName, "vel_x");
            VelY = new global::SpacetimeDB.Col<PersistedEntity, float>(tableName, "vel_y");
            VelZ = new global::SpacetimeDB.Col<PersistedEntity, float>(tableName, "vel_z");
            Epoch = new global::SpacetimeDB.Col<PersistedEntity, uint>(tableName, "epoch");
            ServerDriven = new global::SpacetimeDB.Col<PersistedEntity, bool>(tableName, "server_driven");
            Owned = new global::SpacetimeDB.Col<PersistedEntity, bool>(tableName, "owned");
            Name = new global::SpacetimeDB.Col<PersistedEntity, string>(tableName, "name");
            State = new global::SpacetimeDB.Col<PersistedEntity, System.Collections.Generic.List<byte>>(tableName, "state");
            Version = new global::SpacetimeDB.Col<PersistedEntity, ulong>(tableName, "version");
            SavedAt = new global::SpacetimeDB.Col<PersistedEntity, SpacetimeDB.Timestamp>(tableName, "saved_at");
            SavedBy = new global::SpacetimeDB.Col<PersistedEntity, string>(tableName, "saved_by");
        }
    }

    public sealed class PersistedEntityIxCols
    {
        public global::SpacetimeDB.IxCol<PersistedEntity, string> Key { get; }
        public global::SpacetimeDB.IxCol<PersistedEntity, string> ContainerId { get; }
        public global::SpacetimeDB.IxCol<PersistedEntity, string> CarrierKey { get; }

        public PersistedEntityIxCols(string tableName)
        {
            Key = new global::SpacetimeDB.IxCol<PersistedEntity, string>(tableName, "key");
            ContainerId = new global::SpacetimeDB.IxCol<PersistedEntity, string>(tableName, "container_id");
            CarrierKey = new global::SpacetimeDB.IxCol<PersistedEntity, string>(tableName, "carrier_key");
        }
    }
}
